export default {
  IVIEW_TOP_TEXT_COLOR: '#b99a7c',
  IVIEW_TOP_ACTIVE_TEXT_COLOR: '#f6ca9d',
  IVIEW_TOP_BACKGROUND_COLOR: '#1d1e23',
  IVIEW_LEFT_TEXT_COLOR: '#d0d0d0',
  IVIEW_LEFT_ACTIVE_TEXT_COLOR: '#fff',
  IVIEW_LEFT_BACKGROUND_COLOR: '#1d1e23',

  VUE_TOP_TEXT_COLOR: '#fff',
  VUE_TOP_ACTIVE_TEXT_COLOR: '#41b883',
  VUE_TOP_BACKGROUND_COLOR: '#545c64',
  VUE_LEFT_TEXT_COLOR: '#fff',
  VUE_LEFT_ACTIVE_TEXT_COLOR: '#41b883',
  VUE_LEFT_BACKGROUND_COLOR: '#545c64',
}
